# The URL the site will be built for
base_url = "https://nomacs.org"
title = "nomacs - Image Lounge"
description = "nomacs is a free, open source image viewer, which supports multiple platforms"

theme = "hallo"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feed = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
greeting = "nomacs - Image Lounge"
message = "We are in process of migrating our website. For the time being, please visit our GitHub page."
authorname = "nomacs maintainers"
links = [
    { title = "E-Mail", url = "mailto:info@nomacs.org", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com/nomacs/nomacs", icon = "github" },
]

[extra.theme]
background = "#f7fade" #"#0b93c0" #"#6FCDBD"
foreground = "#0b93c0" #"#f1f4d8" #"#FFF" # text and portrait border
hover = "#a2ac85" #"#333" # link hover
